- id: All_Gone
  alias: All Gone
  trigger:
    platform: state
    entity_id: group.chandler_family
    from: home
    to: not_home
  action:
    service: climate.set_preset_mode
    data:
      entity_id: climate.main_floor,climate.upstairs
      preset_mode: away
- id: All_Home
  alias: All Home
  trigger:
    platform: state
    entity_id: group.chandler_family
    from: not_home
    to: home
  action:
    service: climate.set_preset_mode
    data:
      entity_id: climate.main_floor,climate.upstairs
      preset_mode: home
- id: Hannah_Home
  alias: Hannah Home
  trigger:
  - entity_id: device_tracker.hannah
    from: not_home
    platform: state
    to: home
  action:
  - data:
      entity_id: light.hue_color_lamp_1_5
    service: light.turn_on
  - data:
      entity_id: light.hue_color_lamp_2_5
    service: light.turn_on
- id: Jonathan_Home
  alias: Jonathan Home
  trigger:
  - entity_id: device_tracker.jonathan
    from: not_home
    platform: state
    to: home
  action:
  - data:
      entity_id: light.hue_color_lamp_1_3
    service: light.turn_on
  - data:
      entity_id: light.hue_color_lamp_2_3
    service: light.turn_on
- id: Kids_Gone
  alias: Kids Gone
  trigger:
  - entity_id: group.kids
    from: home
    platform: state
    to: not_home
  action:
  - data:
      entity_id: climate.upstairs
      preset_mode: away
    service: climate.set_preset_mode
  - data:
      entity_id: light.hue_color_lamp_1_3
    service: light.turn_off
  - data:
      entity_id: light.hue_color_lamp_2_3
    service: light.turn_off
  - data:
      entity_id: light.hue_color_lamp_1_4
    service: light.turn_off
  - data:
      entity_id: light.hue_color_lamp_2_4
    service: light.turn_off
  - data:
      entity_id: light.hue_color_lamp_1_5
    service: light.turn_off
  - data:
      entity_id: light.hue_color_lamp_2_5
    service: light.turn_off
- id: Kids_Home
  alias: Kids Home
  trigger:
    platform: state
    entity_id: group.kids
    from: not_home
    to: home
  action:
    service: climate.set_preset_mode
    data:
      entity_id: climate.upstairs
      preset_mode: home
- id: Parents_Gone
  alias: Parents Gone
  trigger:
    entity_id: group.parents
    from: home
    platform: state
    to: not_home
  action:
  - entity_id: light.hue_color_lamp_1
    service: light.turn_off
  - entity_id: light.hue_color_lamp_2
    service: light.turn_off
  - entity_id: light.hue_color_lamp_3
    service: light.turn_off
  - entity_id: light.hue_color_lamp_4
    service: light.turn_off
  - entity_id: switch.fountain
    service: switch.turn_off
- id: Parents_Home
  alias: Parents Home
  trigger:
    entity_id: group.parents
    from: not_home
    platform: state
    to: home
  action:
  - entity_id: light.hue_color_lamp_1
    service: light.turn_on
  - entity_id: light.hue_color_lamp_2
    service: light.turn_on
  - entity_id: light.hue_color_lamp_3
    service: light.turn_on
  - entity_id: light.hue_color_lamp_4
    service: light.turn_on
  - entity_id: switch.fountain
    service: switch.turn_on
- id: Timothy_Home
  alias: Timothy Home
  trigger:
  - entity_id: person.timothy
    from: not_home
    platform: state
    to: home
  condition:
  - after: sunset
    before: sunrise
    condition: sun
  action:
  - data: {}
    entity_id: light.timothy_s_bedroom
    service: light.turn_on
- id: Towel_Rack_On
  alias: Towel Rack On
  trigger:
  - at: 07:45:00
    platform: time
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  action:
  - entity_id: switch.towel_rack
    service: switch.turn_on
- id: Towel_Rack_Done
  alias: Towel Rack Off
  trigger:
    platform: time
    at: '12:00:00'
  action:
  - entity_id: switch.towel_rack
    service: switch.turn_off
- id: Fountain_Start
  alias: Fountain Start
  trigger:
    platform: time
    at: 06:00:00
  action:
  - service: switch.turn_on
    entity_id: switch.fountain
- id: Aquarium_Good_Night
  alias: Aquarium Good Night
  trigger:
  - entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: '-10'
    platform: numeric_state
  condition:
  - after: '12:00:00'
    condition: time
  action:
  - service: light.turn_off
    entity_id: light.aquarium_white
    data:
      transition: '300'
  - service: light.turn_on
    entity_id: light.aquarium_color
    data:
      effect: stop
      transition: '300'
      rgb_color:
      - 0
      - 0
      - 255
      brightness: '5'
- id: Aquarium_Good_Morning
  alias: Aquarium Good Morning
  trigger:
  - above: '5'
    entity_id: sun.sun
    platform: numeric_state
    value_template: '{{ state.attributes.elevation }}'
  condition:
  - before: '12:00:00'
    condition: time
  action:
  - data:
      brightness: '255'
      transition: '900'
    entity_id: light.aquarium_white
    service: light.turn_on
  - data:
      effect: stop
      brightness: '255'
      rgb_color:
      - 255
      - 255
      - 255
      transition: '900'
    entity_id: light.aquarium_color
    service: light.turn_on
- id: Aquarium_Good_Evening
  alias: Aquarium Good Evening
  trigger:
  - below: '18'
    entity_id: sun.sun
    platform: numeric_state
    value_template: '{{ state.attributes.elevation }}'
  condition:
  - after: '12:00:00'
    condition: time
  action:
  - data:
      brightness: '64'
      transition: '900'
    entity_id: light.aquarium_white
    service: light.turn_on
  - data:
      effect: stop
      brightness: '155'
      rgb_color:
      - 0
      - 128
      - 255
      transition: '900'
    entity_id: light.aquarium_color
    service: light.turn_on
- id: '1577987801749'
  alias: Timothy Gone
  description: ''
  trigger:
  - entity_id: person.timothy
    from: home
    platform: state
    to: not_home
  condition: []
  action:
  - entity_id: light.timothy_s_bedroom
    service: light.turn_off
- id: '1578203742772'
  alias: Parents Wind Down
  description: Turn the lights down in parents' room
  trigger:
  - at: '22:30'
    platform: time
  condition: []
  action:
  - data:
      group_name: Master Bedroom
      scene_name: Relax
    service: hue.hue_activate_scene
  - data:
      brightness: 10
      transition: 1200
    entity_id: light.master_bedroom
    service: light.turn_on
  - data:
      transition: 1800
    entity_id: light.master_bedroom
    service: light.turn_off
- id: '1578205391787'
  alias: Master Off
  description: Rig for nighttime operations
  trigger:
  - at: '23:00'
    platform: time
  condition: []
  action:
  - entity_id: switch.fountain
    service: switch.turn_off
  - entity_id: switch.towel_rack
    service: switch.turn_off
  - entity_id: light.living_room
    service: light.turn_off
- id: '1578206082335'
  alias: Master On
  description: Rig for daytime operations
  trigger:
  - at: 06:00
    platform: time
  condition: []
  action:
  - data:
      brightness: 150
    entity_id: light.living_room
    service: light.turn_on
  - data: {}
    entity_id: switch.fountain
    service: switch.turn_on
- id: '1578208769250'
  alias: Sunday Morning Opening
  description: ''
  trigger:
  - at: 07:30
    platform: time
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'off'
  action:
  - data:
      brightness_pct: 100
    entity_id: light.living_room
    service: light.turn_on
  - data: {}
    entity_id: switch.fountain
    service: switch.turn_on
  - entity_id: switch.towel_rack
    service: switch.turn_on
- id: '1587167184256'
  alias: Hydroponic lights on
  description: ''
  trigger:
  - at: '6:00'
    platform: time
  condition: []
  action:
  - type: turn_on
    device_id: df36b3f7195a11eb8c061ddb72561023
    entity_id: light.47025163dc4f22c49388
    domain: light
    brightness_pct: 100
  - type: turn_on
    device_id: df33e120195a11eba0187d14428d1f1b
    entity_id: light.47025163dc4f22c49215
    domain: light
    brightness_pct: 100
  - type: turn_on
    device_id: df335698195a11eb933d3db35d3930e8
    entity_id: light.47025163dc4f22c49220
    domain: light
    brightness_pct: 100
  - type: turn_on
    device_id: df34ebeb195a11ebaa76af1631aade49
    entity_id: light.47025163dc4f22c49412
    domain: light
    brightness_pct: 100
  - type: turn_on
    device_id: df33a660195a11eb96e12b09e30e3ee2
    entity_id: light.47025163dc4f22c49446
    domain: light
    brightness_pct: 100
  mode: single
- id: '1587167321653'
  alias: Hydroponic lights off
  description: ''
  trigger:
  - at: '22:00'
    platform: time
  condition: []
  action:
  - type: turn_off
    device_id: df335698195a11eb933d3db35d3930e8
    entity_id: light.47025163dc4f22c49220
    domain: light
  - type: turn_off
    device_id: df36b3f7195a11eb8c061ddb72561023
    entity_id: light.47025163dc4f22c49388
    domain: light
  - type: turn_off
    device_id: df33e120195a11eba0187d14428d1f1b
    entity_id: light.47025163dc4f22c49215
    domain: light
  - type: turn_off
    device_id: df34ebeb195a11ebaa76af1631aade49
    entity_id: light.47025163dc4f22c49412
    domain: light
  - type: turn_off
    device_id: df33a660195a11eb96e12b09e30e3ee2
    entity_id: light.47025163dc4f22c49446
    domain: light
  mode: single
- id: '1602553067183'
  alias: Turn the desk strip lights on
  description: ''
  trigger:
  - platform: time
    at: 09:00:00
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'on'
  action:
  - service: light.turn_on
    data:
      rgb_color:
      - 255
      - 255
      - 0
      brightness_pct: 100
    entity_id: light.desk
  mode: single
- id: '1602553603932'
  alias: Turn strip lights off after work
  description: ''
  trigger:
  - platform: time
    at: '17:00:00'
  condition:
  - condition: time
    after: '16:59:59'
    weekday:
    - fri
  action:
  - type: turn_off
    device_id: 4a84d1220ceb11eb9040e94609eb8f38
    entity_id: light.desk
    domain: light
  mode: single
- id: '1602553767348'
  alias: Turn strip lights off after school
  description: ''
  trigger:
  - platform: time
    at: '21:20:00'
  condition:
  - condition: time
    after: '21:19:59'
    weekday:
    - mon
    - tue
    - wed
    - thu
  action:
  - type: turn_off
    device_id: 4a84d1220ceb11eb9040e94609eb8f38
    entity_id: light.desk
    domain: light
  mode: single
