- platform: html5
  name: Chandler_Home_Assistant
  #gcm_api_key: !secret google_api_key
  #gcm_sender_id: !secret google_sender_id
  vapid_pub_key: !secret vapid_pub_key
  vapid_prv_key: !secret vapid_priv_key
  vapid_email: !secret vapid_email
